name: Trivy Scan

on:
  workflow_call:
    inputs:
      os_version:
        description: Runner que vai rodar o job
        default: ubuntu-latest
        required: false
        type: string
      container_name:
        description: Container que vai rodar o job
        default: maven:3.9.6-eclipse-temurin-17
        required: false
        type: string
      trivy_version:
        description: Versão do trivy
        default: v0.68.2
        required: false
        type: string
      artifact_name:
        description: Nome do artefato gerado para upload
        default: trivy-scan-results
        required: false
        type: string

jobs:
  trivy-scan:
    name: Trivy-scan

    runs-on: ${{ inputs.os_version }}
    container: ${{ inputs.container_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
        with:
          trivy-version: ${{ inputs.trivy_version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Executa o scan de filesystem no repositório
      - name: Run File System Scan
        run: |
          trivy fs --format sarif \
                   --output trivy-results.sarif \
                   .

      # Envia arquivos gerados pelo build para a seção de Artifacts da execução (para testes locais)
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: trivy-results.sarif

      # Envia a analise para a aba de segurança
      - name: Publish Report to Security Tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif