author: Heitor Giussani Dalla Villa
name: Checkout (composite)
description: Faz checkout do código com fetch-depth configurável

inputs:
  fetch-depth:
    description: Profundidade de histórico para o checkout
    # required: true / e não existir default, a execução FALHA ANTES DE RODAR OS STEPS
    required: false # nao retornarão automaticamente um erro se a entrada não for especificada
    default: "0"

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}