spring.application.name=SpringDemo

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/spring_project
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop