spring.application.name=SpringDemo

# Postgres
#spring.datasource.url=jdbc:postgresql://localhost:5433/spring_project
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=heitor
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true