name: Build and Push Artifact

on:
  workflow_call:
    inputs:
      os_version:
        description: Runner que vai rodar o job
        default: ubuntu-latest
        required: false
        type: string
      environment_name:
        description: Nome do ambiente que vai rodar o job
        default: production
        required: false
        type: string
      sdk_version:
        description: Versão do SDK do GCP
        default: '>= 363.0.0'
        required: false
        type: string

      REGION:
        description: Nome da região meu Artifact Registry
        default: us-west4
        required: false
        type: string
      PROJECT_ID:
        description: Id do projeto
        default: meta-coral-473420-b8
        required: false
        type: string
      REPOSITORY:
        description: Nome do repositório do Artifact Registry
        default: library-ops
        required: false
        type: string
      IMAGE_NAME:
        description: Nome da Imagem Docker
        default: my-app
        required: false
        type: string
      TAG_NAME:
        description: Nome da tag da Imagem Docker
        default: ${{ github.sha }}
        required: false
        type: string

    secrets:
      WIF_PROVIDER:
        required: true
      WIF_SERVICE_ACCOUNT:
        required: true

jobs:
  build-push-artifact:
    name: Build and Push Docker image

    runs-on: ${{ inputs.os_version }}

    environment: ${{ inputs.environment_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: ${{ inputs.sdk_version }}

      - name: Validate Cloud CLI Installation
        run: gcloud info

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker ${{ inputs.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        # registry/project/repository/image:tag
        run: docker build -t ${{ inputs.REGION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.TAG_NAME }} .

      - name: Push Docker Image
        run: docker push ${{ inputs.REGION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.TAG_NAME }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ inputs.IMAGE_NAME }}
          region: ${{ inputs.REGION }}
          image: ${{ inputs.REGION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.REPOSITORY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.TAG_NAME }}
          flags: '--allow-unauthenticated'