name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Permite rodar o workflow manualmente
  workflow_dispatch:

  # Agenda a execução do pipeline
  schedule:
    # Vai rodar todo dias as 15:00 horas (minuto, hora, dia do mês, mês e dia da semana)
    - cron: "0 15 * * *"

# Mudando as permissões especificas da aplicacao
permissions:
  contents: read
  actions: read
  security-events: write

# Dentro do workflow existe 'jobs' (tarefas), e dentro de cada job, há 'steps' (passos) que serão executados em sequência (OS jobs PODEM RODAR EM PARALELO)
jobs:
  build:
    uses: ./.github/workflows/build.yml

    with:
      os_version: 'ubuntu-latest'
      container_name: 'maven:3.9.6-eclipse-temurin-17'
      script_hello_path: './.github/scripts/hello.sh'
      artifact_name: 'app-jar'

  test:
    needs: [ build ]
    uses: ./.github/workflows/test.yml

    with:
      os_version: 'ubuntu-latest'
      container_name: 'maven:3.9.6-eclipse-temurin-17'
      artifact_name: 'checkstyle-report'

  trivy-scan:
    needs: [ build ]
    uses: ./.github/workflows/trivy-scan.yml

    with:
      os_version: 'ubuntu-latest'
      container_name: 'maven:3.9.6-eclipse-temurin-17'
      trivy_version: 'v0.68.2'
      artifact_name: 'trivy-scan-results'

  build-push-artifact:
    needs: [ build, test, trivy-scan ]
    uses: ./.github/workflows/build-push-artifact.yml

    if: ${{ github.ref == 'refs/heads/main' }}

    with:
      os_version: 'ubuntu-latest'
      environment_name: 'production'
      sdk_version: '>= 363.0.0'
      REGION: 'us-west4'
      PROJECT_ID: 'meta-coral-473420-b8'
      REPOSITORY: 'actions-workflow'
      IMAGE_NAME: 'my-app'
      TAG_NAME: ${{ github.sha }}
    secrets:
      CREDENTIALS_JSON: ${{ secrets.GCP_ACCESS_KEY_ID }}