# Workflow básico do github Actions

# Nome do workflow
name: Build Workflow

# Representa como o workflow é ativado para acionar uma trigger para desencadear essa pipeline
on:
  # Aciona uma trigger em eventos de 'push' e 'pull_request', mas apenas para a branch 'main'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Permite rodar o workflow manualmente
  workflow_dispatch:

  # Permite agendar a execução do pipeline
  schedule:
    # Vai rodar todo dias as 15:00 horas (minuto, hora, dia do mês, mês e dia da semana)
    - cron: "0 15 * * *"

# Mudando as permissões para só ter permissão de ler dentro do repositório (pois esta dentro da branch 'main')
permissions:
  contents: read

# Dentro do workflow existe 'jobs' (tarefas), e dentro de cada job, há 'steps' (passos) que serão executados em sequência (OS jobs PODEM RODAR EM PARALELO)
jobs:
  build:
    # Máquina que vai rodar o job (poderia ser uma máquina nas hospedada nos domínios do github, sendo um self‑hosted runner)
    runs-on: ubuntu-latest

    # Lista de passo a passo do job (todos os passos compartilham o mesmo workspace e variaveis de ambiente
    steps:
      # Esse passo faz o checkout do repositório no runner, colocando o código em $GITHUB_WORKSPACE (sem isso os proximos passos nao teriam acesso ao código do repositório) (vai clonar o codigo fonte para dentro do runner)
      - name: Checar o código
        uses: actions/checkout@v4

        # Passar parâmetros de entrada para a ação
        with:
          # Permite obter todo o histórico de commits (útil para checagem de branches)
          fetch-depth: 0

      # Executa múltiplos comandos no shell do ambiente (Ubuntu)
      - name: Executar multiplos comandos shell
        run: |
          echo "Bem vindo ao meu projeto"
          echo "e Hello World!"

#      # Falha o job se houver violações no código-fonte Java
#      - name: Checkstyle (violations)
#        run: mvn -B checkstyle:check

      # Buildar o projeto
      - name: Build Maven
        run: mvn -B install -Dcheckstyle.skip=true

      # Serve para enviar arquivos gerados pelo build para a seção de Artifacts da execução (para testes locais)
      - name: Upload do Build Artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: app-war
          path: target/*.war

      # Se qualquer dos passos anteriores falhou, o valor será verdadeiro
      - name: Notificar se o build falhar
        # sucess() - executa o 'step' se TODOS os processos anteriores tiverem sido bem-sucedidos (PADRÃO)
        # always() - faz com que o job seja executado SEMPRE, independentemente do status anterior
        # failure() - executa o 'step' apenas se o passo anterior falhar
        # cancelled() - executa o 'step' se o workflow for cancelado
        if: failure()
        run: echo "O Build do job falhou! Favor checar os logs."

  testing:
    runs-on: ubuntu-latest

    # Necessário caso queira executar uma tarefa antes da outra (impedindo que as tarefas iniciem paralelamente)
    # Ele depende do build, ou seja, se falhar, ele da skip automaticamente
    needs: build

    # Lista de passo a passo do job (todos os passos compartilham o mesmo workspace e variaveis de ambiente
    steps:
      # Esse passo faz o checkout do repositório no runner, colocando o código em $GITHUB_WORKSPACE (sem isso os proximos passos nao teriam acesso ao código do repositório) (vai clonar o codigo fonte para dentro do runner)
      - name: Checar o código
        uses: actions/checkout@v4

        # Passar parâmetros de entrada
        with:
          # Permite obter todo o histórico de commits (útil para checagem de branches)
          fetch-depth: 0

      # Executar os testes do projeto apenas quanto o ref = refs/heads/main (PORQUE EU QUERO RODAR TESTES APENAS NA BRANCH 'main')
      - name: Rodar os testes dentro da branch 'main'
        # Verificando se a branch atual for 'main'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: mvn -B test

      # Vai analisar o código fonte para garantir regras de formatação e gerar um relatório HTML
      - name: Checkstyle
        if: ${{ github.ref == 'refs/heads/main' }}
        run: mvn -B checkstyle:checkstyle

      # Vai disponibilizar o relatório como um Artifacts
      - name: Disponibilizando artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: |
            target/site/checkstyle.html
            target/checkstyle-result.xml

      # Vai validar se a branch é diferente da 'main'
      - name: Executar testes em outras branches
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "Pulando os testes unitários e análise de código"

  # Job para fazer um 'Security Scan' com a ferramenta open-source trivy
  trivy-scan:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checar o código
        uses: actions/checkout@v4

        with:
          fetch-depth: 0

      - name: Rodar o trivy para escaneamento
        uses: aquasecurity/trivy-action@0.33.1

        with:
          # (file system)
          scan-type: 'fs'
          # referência para escaneamento (diretório atual)
          scan-ref: .
          format: 'json'
          # significa que é para continuar para o próximo passo mesmo que encontre vulnerabilidades
          exit-code: '0'
          vuln-type: 'os,library'
          # armazenar porque assim que uma ação finaliza, a saída também desaparece
          output: 'trivy-results.json'
          version: 'v0.64.0'

        env:
          GITHUB_TOKEN: ${{ secrets.GTIHUB_TOKEN }} # evitar rate limit no download do release

        # Vamos armazenar a saída como um artefato

      # Serve para enviar arquivos gerados pelo build para a seção de Artifacts da execução (para testes locais)
      - name: Upload do escaneamento (trivy) como um artefato
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json